name: Directory and File Manipulation
on:
  workflow_dispatch

jobs:
  files:
    runs-on: ubuntu-latest
    steps:
     - run: mkdir files
     - run: echo "dit is een testfile." > files/test.txt
     - run: ls files
