name: Issue Trigger
on:
  issues:
    types: [opened]

jobs:
  log_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Show issue title en body
        run: |
          echo "Issue title: ${{ github.event.issue.title }}"
          echo "Issue body: ${{ github.event.issue.body }}"
